Fetch data
malinovaya0iriska/for-js pull request #6
Opened 2021-12-15 11:26 UTC by malinovaya0iriska

2021-12-16 06:52 UTC, igorTT requested changes
В целом всё отлично. Небольшие изменения

2021-12-16 06:52 UTC, igorTT commented on index.js
> +  .then((json) => generateTableBody(body, json));
Завернём это в функцию. Адресс сохраним в константу, передадим как параметр

2021-12-16 06:52 UTC, igorTT commented on index.js
> +  return String(set.size);
Обязательно переводить в строку?

2021-12-16 06:52 UTC, igorTT commented on index.js
> +}
Работает но разберём подробнее

2021-12-16 07:21 UTC, malinovaya0iriska commented on index.js
> +}
Здесь логическая ошибка. По пути домой осенило, что не будет корректно считать нечетное количество повторяющихся букв. Переделала на другой вариант.

2021-12-16 07:34 UTC, malinovaya0iriska commented on index.js
> +  return String(set.size);
Необязательно здесь. но вообще просит тип данных строку document.createTextNode. Есть еще вариант с шаблонной строкой в качестве аргумента для неё.  типо такого `${countUniqueLetters(body)}`

2021-12-17 06:38 UTC, igorTT requested changes

2021-12-17 06:38 UTC, igorTT commented on index.js
> +};
Давай избавимся от generateTableBody зависимости. Просто вернём данные. То есть функция у нас должна принимать только url и возвращать данные. Ну и соответственно поменяем ей название.

2021-12-17 06:42 UTC, igorTT commented on index.js
> +  });
Решение работает, но тут получилось О**2 сложность
https://www.freecodecamp.org/news/big-o-notation-why-it-matters-and-why-it-doesnt-1674cfa8a23c/

2021-12-20 16:34 UTC, igorTT approved these changes

2021-12-20 16:34 UTC, merged