feat: implement loader during fetch data
malinovaya0iriska/for-js pull request #9
Opened 2021-12-21 09:31 UTC by malinovaya0iriska

2021-12-21 16:59 UTC, igorTT requested changes

2021-12-21 16:59 UTC, igorTT commented on index.js
> +  setTimeout(() => fetch(URL)
Зачем тут setTimeout?

2021-12-21 16:59 UTC, igorTT commented on loading.js
> +
В описание написано, что надо использовать надпись 'Loading...'

2021-12-21 16:59 UTC, igorTT commented on loading.js
> +  ).style.display = visible ? 'auto' : 'none';
Отображением элементов будем управлять через dom объекты, а не через css

2021-12-22 10:58 UTC, malinovaya0iriska commented on loading.js
> +
поняла, переделаю всё по ТЗ

2021-12-22 10:58 UTC, malinovaya0iriska commented on index.js
> +  setTimeout(() => fetch(URL)
для визуализации лоадера) чтоб посмотреть на улиточку)

2021-12-22 10:58 UTC, malinovaya0iriska commented on loading.js
> +  ).style.display = visible ? 'auto' : 'none';
тоже переделаю

2021-12-22 17:33 UTC, igorTT requested changes

2021-12-22 17:33 UTC, igorTT commented on table.js
> +async function fillTableData(body) {
Надо заменить на const fillTableData = ...

2021-12-22 17:33 UTC, igorTT commented on table.js
> +}
;

2021-12-22 17:33 UTC, igorTT commented on table.js
> +  const newTag = document.createElement(childEl);
childEl -> tagName

2021-12-23 05:54 UTC, igorTT approved these changes

2021-12-23 05:54 UTC, merged